// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using user_admin.Data;

#nullable disable

namespace user_admin.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("user_admin.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("cargos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = false,
                            IdUsuarioCreacion = 0,
                            Nombre = "Desarrollador"
                        },
                        new
                        {
                            Id = 2,
                            Activo = false,
                            IdUsuarioCreacion = 0,
                            Nombre = "Analista"
                        },
                        new
                        {
                            Id = 3,
                            Activo = false,
                            IdUsuarioCreacion = 0,
                            Nombre = "Project Manager"
                        },
                        new
                        {
                            Id = 4,
                            Activo = false,
                            IdUsuarioCreacion = 0,
                            Nombre = "Product Owner"
                        },
                        new
                        {
                            Id = 5,
                            Activo = false,
                            IdUsuarioCreacion = 0,
                            Nombre = "QA"
                        });
                });

            modelBuilder.Entity("user_admin.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = false,
                            IdUsuarioCreacion = 0,
                            Nombre = "TI"
                        },
                        new
                        {
                            Id = 2,
                            Activo = false,
                            IdUsuarioCreacion = 0,
                            Nombre = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 3,
                            Activo = false,
                            IdUsuarioCreacion = 0,
                            Nombre = "Redes"
                        },
                        new
                        {
                            Id = 4,
                            Activo = false,
                            IdUsuarioCreacion = 0,
                            Nombre = "NOC"
                        },
                        new
                        {
                            Id = 5,
                            Activo = false,
                            IdUsuarioCreacion = 0,
                            Nombre = "Soporte"
                        });
                });

            modelBuilder.Entity("user_admin.Models.UsuarioModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("CargoId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCargo")
                        .HasColumnType("int");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("IdCargo");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Email = "Savion_Johnson33@hotmail.com",
                            IdCargo = 1,
                            IdDepartamento = 5,
                            PrimerApellido = "Turcotte",
                            PrimerNombre = "Bernadette",
                            SegundoApellido = "Christiansen",
                            SegundoNombre = "Camila",
                            Usuario = "Hermann9"
                        },
                        new
                        {
                            Id = 101,
                            Email = "Dariana.Windler@yahoo.com",
                            IdCargo = 5,
                            IdDepartamento = 2,
                            PrimerApellido = "Moore",
                            PrimerNombre = "Shanny",
                            SegundoApellido = "Bechtelar",
                            SegundoNombre = "Morton",
                            Usuario = "Francisco94"
                        },
                        new
                        {
                            Id = 102,
                            Email = "Aryanna12@yahoo.com",
                            IdCargo = 2,
                            IdDepartamento = 1,
                            PrimerApellido = "Boyer",
                            PrimerNombre = "Clarabelle",
                            SegundoApellido = "Dach",
                            SegundoNombre = "Esteban",
                            Usuario = "Freida47"
                        },
                        new
                        {
                            Id = 103,
                            Email = "Zetta.Brown@hotmail.com",
                            IdCargo = 1,
                            IdDepartamento = 1,
                            PrimerApellido = "Okuneva",
                            PrimerNombre = "Erling",
                            SegundoApellido = "Runolfsson",
                            SegundoNombre = "Nathanial",
                            Usuario = "Cooper51"
                        },
                        new
                        {
                            Id = 104,
                            Email = "Mireille39@yahoo.com",
                            IdCargo = 3,
                            IdDepartamento = 1,
                            PrimerApellido = "Kreiger",
                            PrimerNombre = "Orin",
                            SegundoApellido = "Hauck",
                            SegundoNombre = "Cesar",
                            Usuario = "Catherine_Kling28"
                        },
                        new
                        {
                            Id = 105,
                            Email = "Hubert27@yahoo.com",
                            IdCargo = 4,
                            IdDepartamento = 2,
                            PrimerApellido = "Bogan",
                            PrimerNombre = "Yolanda",
                            SegundoApellido = "Bruen",
                            SegundoNombre = "Felix",
                            Usuario = "Abe78"
                        },
                        new
                        {
                            Id = 106,
                            Email = "Jordyn97@hotmail.com",
                            IdCargo = 5,
                            IdDepartamento = 2,
                            PrimerApellido = "Bins",
                            PrimerNombre = "Gregory",
                            SegundoApellido = "Lesch",
                            SegundoNombre = "Scot",
                            Usuario = "Gust.Mante31"
                        },
                        new
                        {
                            Id = 107,
                            Email = "Ernie54@hotmail.com",
                            IdCargo = 5,
                            IdDepartamento = 3,
                            PrimerApellido = "Ritchie",
                            PrimerNombre = "Arvid",
                            SegundoApellido = "Daniel",
                            SegundoNombre = "Jerald",
                            Usuario = "Ilene.Olson"
                        },
                        new
                        {
                            Id = 108,
                            Email = "Trey_Bode@hotmail.com",
                            IdCargo = 2,
                            IdDepartamento = 5,
                            PrimerApellido = "Beatty",
                            PrimerNombre = "Camren",
                            SegundoApellido = "Auer",
                            SegundoNombre = "Willis",
                            Usuario = "Tania.Batz9"
                        },
                        new
                        {
                            Id = 109,
                            Email = "Kenya83@yahoo.com",
                            IdCargo = 5,
                            IdDepartamento = 4,
                            PrimerApellido = "Strosin",
                            PrimerNombre = "Roslyn",
                            SegundoApellido = "Bergnaum",
                            SegundoNombre = "Rhoda",
                            Usuario = "Marcellus.Murphy47"
                        },
                        new
                        {
                            Id = 110,
                            Email = "Tyshawn.Braun33@gmail.com",
                            IdCargo = 4,
                            IdDepartamento = 1,
                            PrimerApellido = "Gerhold",
                            PrimerNombre = "Peter",
                            SegundoApellido = "Walter",
                            SegundoNombre = "Jayne",
                            Usuario = "Erik_Denesik87"
                        },
                        new
                        {
                            Id = 111,
                            Email = "Brody.Olson0@yahoo.com",
                            IdCargo = 1,
                            IdDepartamento = 1,
                            PrimerApellido = "Bergstrom",
                            PrimerNombre = "Jennings",
                            SegundoApellido = "Christiansen",
                            SegundoNombre = "Nicolas",
                            Usuario = "Janis99"
                        },
                        new
                        {
                            Id = 112,
                            Email = "Kailee.Homenick@gmail.com",
                            IdCargo = 5,
                            IdDepartamento = 1,
                            PrimerApellido = "Nitzsche",
                            PrimerNombre = "Coleman",
                            SegundoApellido = "Stamm",
                            SegundoNombre = "Alexandro",
                            Usuario = "Viva10"
                        },
                        new
                        {
                            Id = 113,
                            Email = "Rosina36@yahoo.com",
                            IdCargo = 1,
                            IdDepartamento = 3,
                            PrimerApellido = "Lang",
                            PrimerNombre = "Sebastian",
                            SegundoApellido = "Frami",
                            SegundoNombre = "Gerard",
                            Usuario = "Percy93"
                        },
                        new
                        {
                            Id = 114,
                            Email = "Orie_DuBuque@gmail.com",
                            IdCargo = 5,
                            IdDepartamento = 1,
                            PrimerApellido = "Nicolas",
                            PrimerNombre = "Cordelia",
                            SegundoApellido = "Bayer",
                            SegundoNombre = "Duane",
                            Usuario = "Kurtis.Emmerich"
                        },
                        new
                        {
                            Id = 115,
                            Email = "Martina_Cronin@gmail.com",
                            IdCargo = 1,
                            IdDepartamento = 2,
                            PrimerApellido = "Ebert",
                            PrimerNombre = "Nathen",
                            SegundoApellido = "Hudson",
                            SegundoNombre = "Yolanda",
                            Usuario = "Jamison94"
                        },
                        new
                        {
                            Id = 116,
                            Email = "Karen.Nienow@yahoo.com",
                            IdCargo = 4,
                            IdDepartamento = 4,
                            PrimerApellido = "Wilderman",
                            PrimerNombre = "Laurie",
                            SegundoApellido = "Hintz",
                            SegundoNombre = "Christ",
                            Usuario = "Isabell.Block56"
                        },
                        new
                        {
                            Id = 117,
                            Email = "Eldred.Buckridge@yahoo.com",
                            IdCargo = 1,
                            IdDepartamento = 5,
                            PrimerApellido = "Kerluke",
                            PrimerNombre = "Tremaine",
                            SegundoApellido = "Gleason",
                            SegundoNombre = "Nico",
                            Usuario = "Jermain.Schowalter"
                        },
                        new
                        {
                            Id = 118,
                            Email = "Mercedes.Brekke91@hotmail.com",
                            IdCargo = 4,
                            IdDepartamento = 2,
                            PrimerApellido = "Torphy",
                            PrimerNombre = "Bertram",
                            SegundoApellido = "Gleichner",
                            SegundoNombre = "Sylvan",
                            Usuario = "Derek_Yundt84"
                        },
                        new
                        {
                            Id = 119,
                            Email = "Tiara0@hotmail.com",
                            IdCargo = 1,
                            IdDepartamento = 5,
                            PrimerApellido = "Lockman",
                            PrimerNombre = "Emily",
                            SegundoApellido = "Wisozk",
                            SegundoNombre = "Rebeca",
                            Usuario = "Burley27"
                        },
                        new
                        {
                            Id = 120,
                            Email = "Reginald.Yost@gmail.com",
                            IdCargo = 1,
                            IdDepartamento = 1,
                            PrimerApellido = "Morissette",
                            PrimerNombre = "Harry",
                            SegundoApellido = "Beahan",
                            SegundoNombre = "Bailey",
                            Usuario = "Dorothy_Mayert"
                        },
                        new
                        {
                            Id = 121,
                            Email = "Ivory_Gaylord16@gmail.com",
                            IdCargo = 3,
                            IdDepartamento = 3,
                            PrimerApellido = "Bartoletti",
                            PrimerNombre = "Emmalee",
                            SegundoApellido = "Purdy",
                            SegundoNombre = "Deanna",
                            Usuario = "Danielle.Satterfield2"
                        },
                        new
                        {
                            Id = 122,
                            Email = "Reta.Kautzer76@gmail.com",
                            IdCargo = 2,
                            IdDepartamento = 5,
                            PrimerApellido = "Cartwright",
                            PrimerNombre = "Charlie",
                            SegundoApellido = "Goyette",
                            SegundoNombre = "Carolina",
                            Usuario = "Sadye_Luettgen"
                        },
                        new
                        {
                            Id = 123,
                            Email = "Dereck6@yahoo.com",
                            IdCargo = 2,
                            IdDepartamento = 1,
                            PrimerApellido = "Doyle",
                            PrimerNombre = "Rupert",
                            SegundoApellido = "Ryan",
                            SegundoNombre = "Sallie",
                            Usuario = "Cicero47"
                        },
                        new
                        {
                            Id = 124,
                            Email = "Hilma69@yahoo.com",
                            IdCargo = 5,
                            IdDepartamento = 2,
                            PrimerApellido = "Jacobson",
                            PrimerNombre = "Waylon",
                            SegundoApellido = "Smith",
                            SegundoNombre = "Terence",
                            Usuario = "Rose.Kuphal23"
                        },
                        new
                        {
                            Id = 125,
                            Email = "Ophelia.Swaniawski66@hotmail.com",
                            IdCargo = 1,
                            IdDepartamento = 5,
                            PrimerApellido = "Mertz",
                            PrimerNombre = "Bobby",
                            SegundoApellido = "Murazik",
                            SegundoNombre = "Paolo",
                            Usuario = "Chelsea.DuBuque93"
                        },
                        new
                        {
                            Id = 126,
                            Email = "Ruthie_Barton@yahoo.com",
                            IdCargo = 3,
                            IdDepartamento = 5,
                            PrimerApellido = "Fisher",
                            PrimerNombre = "Roderick",
                            SegundoApellido = "Hagenes",
                            SegundoNombre = "Ike",
                            Usuario = "Estelle46"
                        },
                        new
                        {
                            Id = 127,
                            Email = "Anderson.Walker@hotmail.com",
                            IdCargo = 4,
                            IdDepartamento = 1,
                            PrimerApellido = "Will",
                            PrimerNombre = "Naomi",
                            SegundoApellido = "Kuhic",
                            SegundoNombre = "Gardner",
                            Usuario = "Leila31"
                        },
                        new
                        {
                            Id = 128,
                            Email = "Walker.Farrell@yahoo.com",
                            IdCargo = 2,
                            IdDepartamento = 5,
                            PrimerApellido = "Lakin",
                            PrimerNombre = "Susana",
                            SegundoApellido = "Mueller",
                            SegundoNombre = "Angelina",
                            Usuario = "Jay.Gutmann87"
                        },
                        new
                        {
                            Id = 129,
                            Email = "Precious.Dooley@yahoo.com",
                            IdCargo = 5,
                            IdDepartamento = 3,
                            PrimerApellido = "Fay",
                            PrimerNombre = "Monroe",
                            SegundoApellido = "Ritchie",
                            SegundoNombre = "Rahsaan",
                            Usuario = "Juwan46"
                        },
                        new
                        {
                            Id = 130,
                            Email = "Emelie_Gorczany@yahoo.com",
                            IdCargo = 1,
                            IdDepartamento = 4,
                            PrimerApellido = "Abbott",
                            PrimerNombre = "Cole",
                            SegundoApellido = "Dooley",
                            SegundoNombre = "Carmela",
                            Usuario = "Marcos.Kuhic19"
                        },
                        new
                        {
                            Id = 131,
                            Email = "Hellen_Prohaska@gmail.com",
                            IdCargo = 4,
                            IdDepartamento = 3,
                            PrimerApellido = "Rolfson",
                            PrimerNombre = "Berneice",
                            SegundoApellido = "Rempel",
                            SegundoNombre = "Adrianna",
                            Usuario = "Jacinto_Lowe"
                        },
                        new
                        {
                            Id = 132,
                            Email = "Dejon_Huels@yahoo.com",
                            IdCargo = 2,
                            IdDepartamento = 5,
                            PrimerApellido = "Zieme",
                            PrimerNombre = "Wilson",
                            SegundoApellido = "Homenick",
                            SegundoNombre = "Heidi",
                            Usuario = "Aric57"
                        },
                        new
                        {
                            Id = 133,
                            Email = "Imogene_Heathcote@yahoo.com",
                            IdCargo = 4,
                            IdDepartamento = 2,
                            PrimerApellido = "Greenfelder",
                            PrimerNombre = "Margaretta",
                            SegundoApellido = "Bayer",
                            SegundoNombre = "Citlalli",
                            Usuario = "Dandre_Marks28"
                        },
                        new
                        {
                            Id = 134,
                            Email = "May60@yahoo.com",
                            IdCargo = 5,
                            IdDepartamento = 4,
                            PrimerApellido = "Haley",
                            PrimerNombre = "Lupe",
                            SegundoApellido = "Ferry",
                            SegundoNombre = "Marietta",
                            Usuario = "Violet.Hartmann"
                        },
                        new
                        {
                            Id = 135,
                            Email = "Javonte.Farrell@hotmail.com",
                            IdCargo = 5,
                            IdDepartamento = 4,
                            PrimerApellido = "Olson",
                            PrimerNombre = "Greg",
                            SegundoApellido = "O'Keefe",
                            SegundoNombre = "Clotilde",
                            Usuario = "Abdiel_Orn"
                        },
                        new
                        {
                            Id = 136,
                            Email = "Coleman.Emmerich5@hotmail.com",
                            IdCargo = 3,
                            IdDepartamento = 1,
                            PrimerApellido = "Rutherford",
                            PrimerNombre = "Maeve",
                            SegundoApellido = "Kihn",
                            SegundoNombre = "Mckayla",
                            Usuario = "Allen8"
                        },
                        new
                        {
                            Id = 137,
                            Email = "Lavern.Quigley98@hotmail.com",
                            IdCargo = 5,
                            IdDepartamento = 5,
                            PrimerApellido = "Oberbrunner",
                            PrimerNombre = "Sylvester",
                            SegundoApellido = "Bernier",
                            SegundoNombre = "Chandler",
                            Usuario = "Lesly.Barton"
                        },
                        new
                        {
                            Id = 138,
                            Email = "Summer99@hotmail.com",
                            IdCargo = 2,
                            IdDepartamento = 1,
                            PrimerApellido = "Towne",
                            PrimerNombre = "Dylan",
                            SegundoApellido = "Emmerich",
                            SegundoNombre = "Quentin",
                            Usuario = "Antonio68"
                        },
                        new
                        {
                            Id = 139,
                            Email = "Nigel_McGlynn@gmail.com",
                            IdCargo = 3,
                            IdDepartamento = 2,
                            PrimerApellido = "Hintz",
                            PrimerNombre = "Kamren",
                            SegundoApellido = "Mohr",
                            SegundoNombre = "Dena",
                            Usuario = "Darren24"
                        },
                        new
                        {
                            Id = 140,
                            Email = "Lonie.OConner34@yahoo.com",
                            IdCargo = 1,
                            IdDepartamento = 5,
                            PrimerApellido = "Lowe",
                            PrimerNombre = "Genoveva",
                            SegundoApellido = "Lueilwitz",
                            SegundoNombre = "Aurelie",
                            Usuario = "Curt37"
                        },
                        new
                        {
                            Id = 141,
                            Email = "Nash_Welch@hotmail.com",
                            IdCargo = 3,
                            IdDepartamento = 4,
                            PrimerApellido = "Pfeffer",
                            PrimerNombre = "Polly",
                            SegundoApellido = "Stracke",
                            SegundoNombre = "Elena",
                            Usuario = "Lucius.Quitzon84"
                        },
                        new
                        {
                            Id = 142,
                            Email = "Hosea.Batz@hotmail.com",
                            IdCargo = 2,
                            IdDepartamento = 5,
                            PrimerApellido = "Wiegand",
                            PrimerNombre = "Cornell",
                            SegundoApellido = "Watsica",
                            SegundoNombre = "Rafael",
                            Usuario = "Tressie30"
                        },
                        new
                        {
                            Id = 143,
                            Email = "Harrison64@gmail.com",
                            IdCargo = 2,
                            IdDepartamento = 4,
                            PrimerApellido = "Kuvalis",
                            PrimerNombre = "Raleigh",
                            SegundoApellido = "Feest",
                            SegundoNombre = "Beau",
                            Usuario = "Patrick54"
                        },
                        new
                        {
                            Id = 144,
                            Email = "Damaris98@gmail.com",
                            IdCargo = 2,
                            IdDepartamento = 3,
                            PrimerApellido = "Rodriguez",
                            PrimerNombre = "Milo",
                            SegundoApellido = "Ratke",
                            SegundoNombre = "Vince",
                            Usuario = "Amalia.Emmerich77"
                        },
                        new
                        {
                            Id = 145,
                            Email = "Martin.Kuhlman78@gmail.com",
                            IdCargo = 5,
                            IdDepartamento = 2,
                            PrimerApellido = "Ebert",
                            PrimerNombre = "Lily",
                            SegundoApellido = "Schneider",
                            SegundoNombre = "Skylar",
                            Usuario = "Armand52"
                        },
                        new
                        {
                            Id = 146,
                            Email = "Heath.Nienow99@hotmail.com",
                            IdCargo = 4,
                            IdDepartamento = 4,
                            PrimerApellido = "Lakin",
                            PrimerNombre = "Torey",
                            SegundoApellido = "Ziemann",
                            SegundoNombre = "Deshawn",
                            Usuario = "Kasey74"
                        },
                        new
                        {
                            Id = 147,
                            Email = "Tyson12@gmail.com",
                            IdCargo = 1,
                            IdDepartamento = 3,
                            PrimerApellido = "Dickinson",
                            PrimerNombre = "Bridie",
                            SegundoApellido = "Schultz",
                            SegundoNombre = "Myrna",
                            Usuario = "Jonathan6"
                        },
                        new
                        {
                            Id = 148,
                            Email = "Jana90@gmail.com",
                            IdCargo = 4,
                            IdDepartamento = 5,
                            PrimerApellido = "Nienow",
                            PrimerNombre = "Drew",
                            SegundoApellido = "Stamm",
                            SegundoNombre = "Ward",
                            Usuario = "Timmy_Green"
                        },
                        new
                        {
                            Id = 149,
                            Email = "Clement_Stiedemann28@hotmail.com",
                            IdCargo = 5,
                            IdDepartamento = 2,
                            PrimerApellido = "Heller",
                            PrimerNombre = "Adam",
                            SegundoApellido = "Mann",
                            SegundoNombre = "Sigmund",
                            Usuario = "Consuelo_Hegmann6"
                        });
                });

            modelBuilder.Entity("user_admin.Models.UsuarioModel", b =>
                {
                    b.HasOne("user_admin.Cargo", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("CargoId");

                    b.HasOne("user_admin.Departamento", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("user_admin.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("user_admin.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("user_admin.Cargo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("user_admin.Departamento", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
